### ISSUE TITLE
Truncate the output - document types

### ISSUE THREAD

**Issue by MM-IR** [SALT-NLP/Bound-Cap-LLM#1]
Hi, thanks for your nice work for prompt-centric analysis to bound large language model's generation capability.

After reading your paper, I still have some questions unaddressed. 

- In terms of the document type in your paper, how can you perform the truncation, with various types, e.g., paragraph, story, or simply one sentence? Especially in your 3.2 subsection, you only mention you perform a max token length of 1024.

Thank you in advance for the help!

**Comment by StevenyzZhang** [comment]
Hi, thanks for your interest!

To clarify, we don't truncate the generated text according to the document type. 
1024 is the upper bound we set for any kind of generation.

To parse the output and count the number of sentences/paragraphs, please refer to the counter function in https://github.com/SALT-NLP/Bound-Cap-LLM/blob/master/utils.py

Let me know if you have more questions.

**Comment by MM-IR** [comment]
Thank you! Let me take a look (will ask more if I have confusions)!

**Comment by MM-IR** [comment]
Thanks! All my confusions have already got addressed!
